export const CHATROOM_DETAILS_REQUEST = "CHATROOM_DETAILS_REQUEST";
export const CHATROOM_DETAILS_SUCCESS = "CHATROOM_DETAILS_SUCCESS";
export const CHATROOM_DETAILS_FAIL = "CHATROOM_DETAILS_FAIL";

export const CHATROOM_CREATE_REQUEST = "CHATROOM_CREATE_REQUEST";
export const CHATROOM_CREATE_SUCCESS = "CHATROOM_CREATE_SUCCESS ";
export const CHATROOM_CREATE_FAIL = "CHATROOM_CREATE_FAIL";
